version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/python/itables_core"
      - "/python/pydatatables"
      - "/python/pyaggrid"
      - "/python/itables"
    schedule:
      interval: "weekly"
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/packages/pyaggrid"
      - "/packages/pyaggrid_anywidget"
      - "/packages/pyaggrid_for_dash"
      - "/packages/pyaggrid_for_streamlit"
    schedule:
      interval: "weekly"
    groups:
      npm-pyaggrid:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/pydatatables"
    schedule:
      interval: "weekly"
    groups:
      npm-pydatatables:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/pydatatables_anywidget"
    schedule:
      interval: "weekly"
    groups:
      npm-pydatatables-anywidget:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/pydatatables_for_dash"
    schedule:
      interval: "weekly"
    groups:
      npm-pydatatables-for-dash:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/pydatatables_for_streamlit"
    schedule:
      interval: "weekly"
    groups:
      npm-pydatatables-for-streamlit:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
