title: Interactive Tables
author: Marc Wouts
copyright: "2019-2025"
logo: "../src/itables/logo/logo.svg"
execute:
  execute_notebooks: force
sphinx:
  config:
    html_extra_path: ['quarto']
    rediraffe_branch: main
    rediraffe_redirects:
      advanced_parameters.md: options/options.md
      extensions.md: options/buttons.md
      select.md: options/select.md
      custom_css.md: css.md
      dash.md: apps/dash.md
      html_export.md: apps/html.md
      shiny.md: apps/shiny.md
      quarto.md: apps/quarto.md
      streamlit.md: apps/streamlit.md
      widget.md: apps/widget.md
      sample_dataframes.md: pandas_dataframes.md
  extra_extensions:
    - sphinxext.rediraffe
repository:
  url: https://github.com/mwouts/itables
  path_to_book: docs
  branch: main
html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
