context:
  version: ${{ env.get("ITABLES_VERSION") }}

package:
  name: itables
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - nodejs
    - python >=3.9
    - python-build
    - hatch-jupyter-builder
    - dash
    - pyyaml
    - hatchling
    - pip
  run:
    - python >=3.9

tests:
  - python:
      imports:
        - itables
      pip_check: true
      python_version: "3.9.*"
  - script:
      - python -c "import itables; print(itables.__version__)"
    requirements:
      run:
        - python =3.9

about:
  homepage: https://github.com/mwouts/itables
  repository: https://github.com/mwouts/itables
  documentation: https://mwouts.github.io/itables
  summary: Python DataFrames as Interactive DataTables
  license: MIT
  license_file:
    - LICENSE
  description: |
    Render Pandas and Polars DataFrames as interactive [DataTables](https://datatables.net/)
    that you can sort, paginate, scroll or filter. ITables works in Jupyter,
    VS Code, Google Colab, Quarto, Marimo, and in many application frameworks like
    Dash, Panel, Shiny, or Streamlit.
